tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
cask_args appdir: "/Applications"

brew "zsh"
brew "git"
brew "git-lfs"
brew "awscli"
brew "aws-vault"
brew "terraform"
brew "tfenv"
brew "ansible"
brew "kubectl"

cask "iterm2"
cask "visual-studio-code"
cask "docker"
cask "google-chrome"
cask "google-cloud-sdk"