# 'brew tap'
tap "aws/tap"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "zsh"
brew "git"
brew "git-lfs"
# brew "python@3.10"
# brew "ansible"
# brew "ansible-lint"
# brew "brew-gem"
# brew "freetype"
# brew "cfn-lint"
# brew "clang-format"
# brew "cloudformation-guard"
# brew "gcc"
# brew "ruby"
# brew "gem-cfn-nag"
# brew "guile"
# brew "unbound"
# brew "gnutls"
# brew "gnupg"
# brew "helm"
# brew "jq"
# brew "jsonnet"
# brew "kubernetes-cli"
# brew "ncurses"
# brew "nodebrew"
# brew "openjdk"
# brew "pyenv"
# brew "python@3.9"
# brew "sshs"
# brew "aws/tap/aws-sam-cli"
# brew "aws/tap/copilot-cli"
# brew "hashicorp/tap/packer"
# brew "hashicorp/tap/terraform"

# cask "virtualbox"
